### ISSUE TITLE
Script should work or give error message

### ISSUE THREAD

**Issue by richelbilderbeek** [kokoichi206/plantuml-to-mermaid#9]
Hi @kokoichi206,

Thanks for putting your code in the open!

Here I put a usecase that may currently be unsupported. Not supporting everything is fine. However, what would be even better is that a user would get an error if something is unsupported.

To reproduce: put [usecase.md](https://github.com/kokoichi206/plantuml-to-mermaid/files/13248611/usecase.md) (content is also showed below) in a folder, then do:

```
bash main.sh usecase.md
```

This will create an empty file called `output.md`

I expected the script either to work or to give an error message.

Thanks and cheers, Richel Bilderbeek

## `usecase.md`

```
@startuml UserSimulation

!define PARTICLE_FIELD class :Particle Field;
!define PARTICLE class :Particle;
!define GRAVITY class :Gravitational Interaction;
!define BOUNDARY class :Boundary Condition;

:User: -down-> (Start Simulation) : Includes
:User: -down-> (Stop Simulation) : Includes
:User: -down-> (Pause Simulation) : Includes
:User: -down-> (Configure Simulation) : Includes
:User: -down-> (View Simulation) : Includes
(Start Simulation) -down-> PARTICLE_FIELD : R1
(Configure Simulation) -down-> PARTICLE : R2
(Configure Simulation) -down-> GRAVITY : R3 (Gravitational)
(Configure Simulation) -down-> BOUNDARY : R4
(Configure Simulation) -down-> (Step Simulation) : Includes
(Pause Simulation) -down-> (Resume Simulation) : Includes
(Step Simulation) -down-> (Advance Simulation) : Includes
(Advance Simulation) -down-> PARTICLE : R3 (Gravitational)
(Advance Simulation) -down-> (Collision Detection) : Includes
(Stop Simulation) -down-> (Exit Simulation) : Includes
(View Simulation) -down-> (Render Frame) : Includes
(Render Frame) -down-> PARTICLE_FIELD : R6
(PARTICLE_FIELD) -down-> PARTICLE : R3 (Gravitational)
(PARTICLE_FIELD) -down-> BOUNDARY : R4

@enduml
```

**Comment by kokoichi206** [comment]
@richelbilderbeek 
Thank you for trying this script and reporting errors.

I apologize for the insufficient documentation; currently, the script functions properly only with the sequence diagrams.
I have updated the README.md accordingly.

I agree with you regarding the error messages, so I have corrected them to display the appropriate messages.

**Comment by richelbilderbeek** [comment]
@kokoichi206 thanks, that is awesome of you! 

Best of wishes, Richel
